spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    database: H2
    hibernate:
      ddl-auto: create-drop


# Turning on statistics
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    show-sql: true

#Show all queries
logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace

#  Enabling H2 Console
  h2:
    console:
      enabled: true

# Turn stats on



